// <auto-generated />
namespace WorkoutWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class User_Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201408080958224_User_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
