// <auto-generated />
namespace WorkoutWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Category));
        
        string IMigrationMetadata.Id
        {
            get { return "201408091603007_Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
